project:
  type: website
  output-dir: docs

website:
  title: "4DM20 Engineering Optimization"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/robertvs333/engineering-optimization

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
